---
title: "correltools"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

The {correltools} :package: aims to provide utility functions for useful plots, analyses and tools in the CorrelAid context.


## Contribute

I (@friep) have collected some mini-projects as [issues](https://github.com/CorrelAid/correltools/issues). For each issue there is a "get started" RMarkdown in `playground` with code how to get example data that you can work with during development. If you want to pick up an issue, just comment under it and I'll assign you! :) 

Depending on your skill levels, I imagine the contributing workflows as follows:

#### no Git experience, no R package development experience

Prerequisites: you know how to work in R on your laptop, you know how to work with R Markdown

1. Download the repository as a zip (by clicking on the green "code" button and "download as zip"). Unzip the directory and double-click on the file `correltools.Rproj` to open the project in RStudio.
2. work in the RMarkdown for your issue in the `playground` folder
3. work until you have something that you think is cool.
4. If you know how to write a R function, try to put your code into a function. If you don't know about functions yet, you can read more about them [here](https://r4ds.had.co.nz/functions.html).


#### Git experience but no R package development experience

Prerequisites: you know about pull-commit-push and (optionally) branching

1. clone the repository (or fork it and work on your own copy and later make a pull request)
2. make a branch for your issue (e.g. issue1-ggplot-theme). If you don't know about branching, you can also work on the `main` branch. Ask Frie to add you as a contributor to the GitHub repo.
3. work in the RMarkdown for your issue in the `playground` folder
4. work until you have something that you think is cool. Commit whenever you feel you have made some progress. 
5. write a function that generates the output in your r markdown. (or multiple functions if necessary)
6. write @frie a message on Slack for guidance and/or read into how you can possibly add your function to the R package by reading https://r-pkgs.org/intro.html

#### Git experience and R package development experience / good experience in R
Prerequisites: you know how to develop R packages (or you are confident you can quickly learn about it by reading [R packages](https://r4ds.had.co.nz/index.html)). You know how to fork and/or how to work on Git branches (or you want to learn about it!).


1. clone the repository (or fork it and work on your own copy and later make a pull request). If you choose the former, ask Frie to add you as a contributor to the GitHub repo.
2. make a branch for your issue (e.g. issue1-ggplot-theme).
3. work in the RMarkdown for your issue in the `playground` folder or directly work in `R` on your function. :) 
4. work until you have something that you think is cool. Commit whenever you feel you have made some progress. 
5. Make a PR if you're ready :)


