---
title: "issue2 - correlaidx map"
author: "Christine"
date: "`r Sys.Date()`"
output: 
  html_document:
      code_folding: show

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(here)
library(tidyverse)
library(glue)
library(sf)
library(leaflet)

```

# Load data

```{r data}

cax_cities <- 
  readr::read_csv("https://raw.githubusercontent.com/CorrelAid/correltools/main/data/example_correlaidx_geo.csv")

cax_links <- 
  map_chr(
    c("berlin/", "bremen/", "cologne/", "dortmund/", "goettingen/", "hamburg/", 
      "karlsruhe/", "konstanz/", "leipzig/", "mannheim/", "munich/", "netherlands/", 
      "paris/", "rhein-main/", "ruhrgebiet/", "stuttgart/", "switzerland/"),
    ~paste0("https://correlaid.org/correlaid-x/", .x)
    ) %>% 
  tibble(
    link = ., 
    chapter = c("Berlin", "Bremen", "Cologne/Bonn", "Dortmund", NA, "Hamburg", 
                "Karlsruhe", "Konstanz", "Leipzig", "Mannheim", "Munich", "Nederland", 
                "Paris", "Rhein-Main", NA, "Stuttgart", "Switzerland")
    )

cntrs <- 
  rnaturalearth::ne_countries(country = c("Germany", "Netherlands", "France", "Switzerland"),
                              scale = "large", returnclass = "sf") %>% 
  st_set_crs(4326)

```

# Define colors

(can be omitted when color function is implemented, see PR by Long)

```{r colors}

correlaid_colours <- list(
  qualitative = c(
    blue = "#3863a2",
    red = "#f04451",
    green = "#96c342",
    teal = "#508994",
    black = "#3c3c3b",
    grey = "#c4c4c4"
  ),
  gradient = c(
    "#bcd259",
    "#96c246",
    "#78a972",
    "#6fa080",
    "#508994",
    "#3665a3",
    "#3c61aa",
    "#2d3b5a"
  ),
  gradient_x = c(
    "#f04451",
    "#e35564",
    "#b65976",
    "#906289",
    "#7b6490",
    "#5b669d",
    "#3665a3",
    "#254e90"
  )
)

correlaid_colors <- correlaid_colours
```

# Data preparation

```{r data-prep}

# CAX data
cities <- cax_cities %>% 
  # Extract lat and lon from geometry column
  mutate(lon = str_remove_all(geometry, "(^c\\()|(\\, .+\\)$)") %>% 
           as.numeric(),
         lat = str_remove_all(geometry, "(^c\\(.+\\, )|(\\)$)") %>% 
           as.numeric()) %>% 
  left_join(cax_links)

# Color palette functions (leaflet package)
pal_cities <- colorFactor(correlaid_colors$gradient, domain = factor(cities$year_founded))

pal_cntrs <- colorFactor(correlaid_colors$gradient_x, domain = cntrs$name)

```

# Leaflet widget

```{r widget}

cax_map <- 
  
  leaflet() %>% 
  
  addProviderTiles(
    providers$CartoDB.Positron,
    options = providerTileOptions(opacity = 0.7)
    ) %>% 
  
  addPolygons(
    data = cntrs,
    fillColor = ~pal_cntrs(name),
    fillOpacity = .3,
    stroke = FALSE
  ) %>% 
  
  addCircles(
    data = cities,
    color = ~pal_cities(factor(year_founded)),
    fillOpacity = .8, 
    radius = 12000,
    highlightOptions = highlightOptions(
      color = "white",
      bringToFront = TRUE
    ),
    popup = ~glue("<b>CorrelaidX {chapter}</b><br/>",
                  "<a href='{link}'>Info &#128279;</a>")
    ) %>%
  
  addLegend(
    data = cities,
    "bottomright", 
    pal = pal_cities, 
    values = ~factor(year_founded),
    title = "Year founded",
    opacity = 1
  ) %>% 
  
  setView(lng = 5.5, lat = 49.5, zoom = 5)

cax_map
```

## Save Widget

```{r save}

htmlwidgets::saveWidget(cax_map, "cax_map.html")

```

# TO DO

- maybe automate CAX link collection
